# Generated by Django 4.2.7 on 2026-04-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('manual', 'Manual WhatsApp'), ('api', 'WhatsApp API'), ('email', 'Email'), ('sms', 'SMS')], default='manual', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_logs', to='orders.order')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
            options={
                'verbose_name': 'Quotation Log',
                'verbose_name_plural': 'Quotation Logs',
                'db_table': 'quotation_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
