# Generated by Django 4.2.7 on 2026-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_quotationlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_user_id_51663a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_to', 'stage'], name='orders_assigne_e37b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stage', 'created_at'], name='orders_stage_7d444c_idx'),
        ),
    ]
