# Generated by Django 4.2.7 on 2026-03-03 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('apply_to', models.CharField(choices=[('product', 'Product'), ('collection', 'Collection'), ('category', 'Category'), ('brand', 'Brand')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brands', models.ManyToManyField(blank=True, related_name='offers', to='products.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='products.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='offers', to='products.collection')),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='products.product')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='offers_is_acti_5de943_idx'), models.Index(fields=['start_date', 'end_date'], name='offers_start_d_3f9be3_idx')],
            },
        ),
    ]
