# Generated by Django 4.2.7 on 2026-03-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured offers appear on homepage (max 4)'),
        ),
    ]
