# Generated by Django 4.2.7 on 2026-03-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_featured'], name='offers_is_feat_efe348_idx'),
        ),
    ]
