# Generated by Django 6.0.3 on 2026-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_update_final_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='apply_to',
            field=models.CharField(choices=[('product', 'Product'), ('collection', 'Category'), ('category', 'Subcategory'), ('brand', 'Brand')], max_length=20),
        ),
    ]
