# Generated by Django 4.2.7 on 2026-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0008_alter_offer_apply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marquee_enabled', models.BooleanField(default=False, help_text='Enable the scrolling offer ticker above the navbar')),
                ('marquee_speed', models.IntegerField(default=40, help_text='Scrolling speed in seconds (lower = faster)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marquee_offers', models.ManyToManyField(blank=True, help_text='Active offers to display in the marquee ticker', related_name='marquee_settings', to='offers.offer')),
            ],
            options={
                'verbose_name': 'Promotion Settings',
                'verbose_name_plural': 'Promotion Settings',
                'db_table': 'promotion_settings',
            },
        ),
    ]
