# Generated by Django 4.2.7 on 2026-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_offer_apply_to'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionsettings',
            name='is_popup_enabled',
            field=models.BooleanField(default=False, help_text='Enable the first-visit welcome offer pop-up'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='popup_offers',
            field=models.ManyToManyField(blank=True, help_text='Active offers to display in the welcome pop-up', related_name='popup_settings', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='promotionsettings',
            name='popup_strategy',
            field=models.CharField(choices=[('single', 'Single Offer'), ('cycle_daily', 'Cycle Daily'), ('cycle_hourly', 'Cycle Hourly')], default='single', help_text='How to cycle through multiple popup offers', max_length=20),
        ),
    ]
