# Generated by Django 4.2.30 on 2026-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_promotionsettings_is_popup_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('performed_by', models.CharField(blank=True, default='', max_length=200)),
                ('filename', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, default='', max_length=20)),
                ('records_created', models.IntegerField(default=0)),
                ('records_overwritten', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('records_renamed', models.IntegerField(default=0)),
                ('records_errors', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backup History',
                'verbose_name_plural': 'Backup History',
                'db_table': 'backup_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
