# Generated by Django 4.2.7 on 2026-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show as featured collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Short tagline for the collection', max_length=200),
        ),
    ]
