# Generated by Django 4.2.7 on 2026-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_is_featured_collection_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_icon_url',
            field=models.URLField(blank=True, default='', help_text='Icon/SVG for featured category display', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured categories section'),
        ),
    ]
