# Generated by Django 4.2.7 on 2026-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_featured_icon_url_category_is_featured'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_popu_ec4582_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Show in bestsellers section'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller'], name='products_is_best_476666_idx'),
        ),
    ]
