# Generated by Django 4.2.7 on 2026-03-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_is_popu_ec4582_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Color variant (e.g., Navy Blue, Walnut Brown)', max_length=100)),
                ('material', models.CharField(help_text='Material variant (e.g., Velvet, Solid Oak)', max_length=100)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling Price', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available stock for this variant')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert threshold for low stock')),
                ('images', models.JSONField(default=list, help_text='Variant-specific images')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default variant to display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ['-is_default', 'color', 'material'],
                'indexes': [models.Index(fields=['sku'], name='product_var_sku_3a95f0_idx'), models.Index(fields=['product', 'is_active'], name='product_var_product_b96575_idx'), models.Index(fields=['is_default'], name='product_var_is_defa_3d8bd4_idx')],
                'unique_together': {('product', 'color', 'material')},
            },
        ),
    ]
