# Generated by Django 4.2.7 on 2026-03-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_color_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_colors', to='products.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_colors', to='products.material')),
            ],
            options={
                'verbose_name': 'Material Color',
                'verbose_name_plural': 'Material Colors',
                'db_table': 'material_colors',
                'ordering': ['material__name', 'color__name'],
                'unique_together': {('material', 'color')},
            },
        ),
    ]
