# Generated by Django 4.2.7 on 2026-03-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_materialcolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialColor',
        ),
    ]
