# Generated by Django 6.0.3 on 2026-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_finalize_category_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frequently_bought_together',
            field=models.ManyToManyField(blank=True, help_text='Products frequently bought together with this one', to='products.product'),
        ),
    ]
