# Generated by Django 6.0.3 on 2026-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopByRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('living', 'Living Room'), ('bedroom', 'Bedroom'), ('dining', 'Dining Room'), ('office', 'Home Office')], help_text='Select one of the fixed room types.', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop by Room',
                'verbose_name_plural': 'Shop by Rooms',
                'db_table': 'shop_by_rooms',
                'ordering': ['room_type'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_cat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_subcat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_brand_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_bestseller_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_hot_selling_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_prod_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_prod_default_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='variant_active_stock_idx',
        ),
        migrations.AddField(
            model_name='shopbyroom',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select products to feature in this room.', related_name='shop_by_rooms', to='products.product'),
        ),
    ]
