# Generated by Django 4.2.7 on 2026-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_shopbyroom_remove_product_product_active_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for inventory valuation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='last_restocked',
            field=models.DateTimeField(blank=True, help_text='Last restock date', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reorder_point',
            field=models.IntegerField(default=10, help_text='Automatic reorder point'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reorder_quantity',
            field=models.IntegerField(default=50, help_text='Quantity to reorder'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reserved_quantity',
            field=models.IntegerField(default=0, help_text='Stock reserved for pending orders'),
        ),
    ]
