# Generated by Django 4.2.7 on 2026-04-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productvariant_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Image showing the material texture/appearance', max_length=500),
        ),
    ]
