# Generated by Django 4.2.7 on 2026-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_add_material_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Display title shown to customers (e.g., "Premium Velvet Fabric")', max_length=200),
        ),
    ]
