# Generated by Django 4.2.7 on 2026-04-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_quotationlog'),
        ('products', '0016_productvariant_cost_price_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('adjustment', 'Manual Adjustment'), ('return', 'Return'), ('damage', 'Damage/Loss'), ('reserved', 'Reserved for Order'), ('released', 'Released from Reserve'), ('transfer', 'Transfer')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for increase, negative for decrease')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='accounts.staff')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='stock_movem_variant_5b86c0_idx'), models.Index(fields=['movement_type', '-created_at'], name='stock_movem_movemen_829843_idx'), models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('overstock', 'Overstock')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('current_quantity', models.IntegerField()),
                ('threshold_quantity', models.IntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='accounts.staff')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'db_table': 'stock_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', 'is_resolved'], name='stock_alert_variant_b8c69e_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='stock_alert_alert_t_6efdea_idx'), models.Index(fields=['priority', 'is_resolved'], name='stock_alert_priorit_bcef39_idx'), models.Index(fields=['created_at'], name='stock_alert_created_9f8b1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Inventory Snapshot',
                'verbose_name_plural': 'Inventory Snapshots',
                'db_table': 'inventory_snapshots',
                'ordering': ['-snapshot_date', 'variant'],
                'indexes': [models.Index(fields=['snapshot_date'], name='inventory_s_snapsho_c3bf17_idx'), models.Index(fields=['variant', 'snapshot_date'], name='inventory_s_variant_ec2fdb_idx')],
                'unique_together': {('variant', 'snapshot_date')},
            },
        ),
    ]
